modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_dynamics"
version = "${file.jarVersion}"
displayName = "Thermal Dynamics"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Thermal gets dynamic!

Contains various logistic options for technical gameplay!
'''
[[dependencies.thermal_dynamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "forge"
mandatory = true
versionRange = "[35.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.2,1.3]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "thermal"
mandatory = true
versionRange = "[1.2,1.3]"
ordering = "AFTER"
side = "BOTH"