org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=thermal_food
mod_name=Thermal Food
mod_license=All Rights Reserved
mod_version=2.1.2
mod_group_id=fdk123.thermalfood
mod_authors=fdk123 and Stimortal
mod_description=Addon foods for Thermal Cultivation.

cofh_core_version=1.20.1-11.0.2.56
thermal_foundation_version=1.20.1-11.0.6.70
thermal_cultivation_version=1.20.1-11.0.1.24
cofh_core_version_range=[11.0.0,12.0.0)
thermal_version_range=[11.0.0,12.0.0)
thermal_cultivation_version_range=[11.0.0,12.0.0)
